name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate image version
      run: echo "IMAGE_VERSION=$(date +%s)" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kaikedev/expense-management:$IMAGE_VERSION --tag kaikedev/expense-management:latest
    
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Docker push
      run: docker push kaikedev/expense-management:$IMAGE_VERSION && docker push kaikedev/expense-management:latest
